version: '3.6'
services:
  build:
    build: &build
      context: .
    volumes:
      - .:/output
    working_dir: /go/src/github.com/remind101/ssm-env
    environment:
      - APP_NAME
      - JENKINS_GITHUB_USERNAME
      - JENKINS_GITHUB_API_TOKEN

  test:
    build:
      <<: *build
    command: make test
